
name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Test with Coverage
      run: mvn -B verify org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
      
    - name: Verify Coverage
      run: |
        COVERAGE=$(grep -o '<tfoot>.*</tfoot>' target/site/jacoco/index.html | grep -o '[0-9][0-9]*%' | head -1 | grep -o '[0-9][0-9]*')
        if [ "$COVERAGE" -lt 100 ]; then
          echo "Test coverage is below 100%: $COVERAGE%"
          exit 1
        else
          echo "Test coverage is 100%"
        fi
      
    - name: Publish Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/site/jacoco/
